### ISSUE TITLE
Penn Treebank format data for the test split

### ISSUE THREAD

**Issue by yuhaozhang** [UCDenver-ccp/craft-st-2019#1]
Hi, thanks a lot for sharing the test split of the CRAFT data!

I noticed that currently for the syntactic annotations, only the converted CoNLL-U format files are released. Do you have any plan to release the Penn Treebank format (.tree) files as was done for the rest of the dataset [in this repo](https://github.com/UCDenver-ccp/CRAFT/tree/master/structural-annotation/treebank/penn)?

Thanks in advance!

**Comment by bill-baumgartner** [comment]
Hi,
Thanks for your question. Yes, there is a plan to release the Penn Treebank data for the 30 test articles. There is an upcoming release of CRAFT that will contain the Penn Treebank data as well as the native file formats for other data for the 30 test articles. The new release will be on the [main CRAFT repository](https://github.com/UCDenver-ccp/CRAFT), and should happen in the next two weeks. I'll respond to this thread when the new release has been posted.

**Comment by yuhaozhang** [comment]
Thanks for the response! Look forward to the new release!

**Comment by yuhaozhang** [comment]
Hi @bill-baumgartner, just want to check in on the progress of this. Is there any updated ETA on this? Thanks in advance for any information!

**Comment by bill-baumgartner** [comment]
Yes, [CRAFT v4.0.0](https://github.com/UCDenver-ccp/CRAFT/releases/tag/v4.0.0) has just been released and includes all annotation files (including the treebank files) for all 97 articles.

**Comment by yuhaozhang** [comment]
Awesome! Thanks again for making these great resources available to the community!
